import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/app/provider";
import TopBar from "@/components/TopBar";
import { NextUIProvider } from "@nextui-org/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className + "bg-[rgb(23,23,23)] flex flex-col max-h-screen h-screen"}>
          <TopBar />
          <div className="h-full flex-grow">
            <ToastContainer hideProgressBar />
            {children}
          </div>
        </body>
      </Provider>
    </html>
  );
}
